environment:
  matrix:
#    - source: https://cloud.r-project.org/src/base/R-latest.tar.gz
#      archive: r-release
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      archive: r-devel
      cran: true
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
      archive: r-patched
      cran: true

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

after_build:
  - 7z a %target%-win.zip %builddir%\*.exe %builddir%\*.log %builddir%\*.html %builddir%\md5sum.* %builddir%\SVN-REVISION.* %builddir%\README.*

artifacts:
  - path: "%target%-win.zip"
    name: Installer Bundle

on_finish:
  - 7z a logs.zip %builddir%\*.log
  - appveyor PushArtifact logs.zip

deploy:
  - provider: Environment
    name: ftp_archive
    target: "%target%"
    archive: "%archive%"
    revision: "%revision%"
    on:
      branch: master

  - provider: Environment
    name: ftp_current
    target: "%target%"
    on:
      branch: master
      cran: true
