environment:
  matrix:
    - source: https://cran.r-project.org/src/base/R-3/R-3.5.3.tar.gz
      RTOOLS_VERSION: 35
      archive: r-release
#    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
#      archive: r-devel
#      cran: true
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
#    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
#      archive: r-patched
#      cran: true

  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22evsMT/KnwtB4NgcYNLJheI
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  CertKit: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert.exe
  KeyFile: C:\jeroen.pfx

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

after_build:
  - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
  - ps: SignFiles "${env:builddir}\${env:target}-win.exe"
  - ps: Remove-Item â€“path $env:KeyFile
  - cd %builddir%
  - md5sum %target%-win.exe > md5sum.txt.%target%
  - cd %startdir%
  - 7z a %target%-win.zip %builddir%\%target%-win.exe %builddir%\md5sum.txt.%target% %builddir%\*.log %builddir%\*.html %builddir%\SVN-REVISION.* %builddir%\README.*

artifacts:
  - path: "%target%-win.zip"
    name: Installer Bundle

on_finish:
  - 7z a logs.zip %builddir%\*.log
  - appveyor PushArtifact logs.zip

deploy:
  - provider: Environment
    name: ftp_archive
    target: "%target%"
    archive: "%archive%"
    revision: "%revision%"
    on:
      branch: master

  - provider: Environment
    name: ftp_current
    target: "%target%"
    on:
      branch: master
      cran: true
